--- 
- 
  hosts: all
  name: "Uses shell module to retrieve data and timestamp from the OS"
  tasks: 
    - 
      name: "Get timestamp from the system"
      register: tstamp
      shell: "date +%Y-%m-%d%H-%M-%S"
