--- 
- 
  hosts: tower-prod.eu.rabonet.com
  name: "Shell Examples"
  tasks: 
    - 
      args: 
        chdir: /etc
      async: 10
      become: true
      name: "Open /etc/passwd file"
      poll: 0
      register: fileout
      shell: "cat passwd"
      tags: fileout
    - 
      debug: "msg=\"{{ fileout.stdout-lines }}\""
